# Generated by Django 3.2.14 on 2022-08-01 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('farm_name', models.CharField(default=None, max_length=24)),
                ('farm_area', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('address_line_one', models.TextField(default=None, max_length=224)),
                ('address_line_two', models.TextField(default=None, max_length=224)),
                ('city', models.CharField(default=None, max_length=24)),
                ('country', models.CharField(default=None, max_length=24)),
                ('town_village', models.CharField(default=None, max_length=24)),
                ('zipcode', models.IntegerField(default=0)),
                ('state', models.CharField(default=None, max_length=24)),
                ('lat', models.IntegerField(default=0)),
                ('lng', models.IntegerField(default=0)),
                ('description', models.TextField(default=None, max_length=224)),
                ('lastupdatedt', models.DateField(auto_now=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='uploads')),
                ('certificate', models.CharField(default=None, max_length=24)),
                ('farm_status', models.CharField(default=None, max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
