# Generated by Django 3.2.14 on 2022-10-04 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farms',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='image',
        ),
        migrations.AlterField(
            model_name='farms',
            name='address_line_one',
            field=models.TextField(default=None, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='address_line_two',
            field=models.TextField(default=None, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='city',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='country',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='createdAt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='description',
            field=models.TextField(default=None, max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='farm_area',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='farm_name',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='farm_status',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='lastupdatedt',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='lat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='lng',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='state',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='town_village',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farms',
            name='zipcode',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='farmimage_uploads')),
                ('image_name', models.CharField(default=None, max_length=24, null=True)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_images', to='farms.farms')),
            ],
        ),
        migrations.CreateModel(
            name='FarmCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(default=None, max_length=24, null=True)),
                ('certificate_number', models.IntegerField(default=0, null=True)),
                ('add_information', models.TextField(default=None, max_length=224, null=True)),
                ('image', models.ImageField(null=True, upload_to='certificate_uploads')),
                ('certificates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='farms.farms')),
            ],
        ),
    ]
