# Generated by Django 3.2.14 on 2022-10-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_auto_20221004_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondConstructType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct_type', models.CharField(default=None, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PondType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=24)),
                ('desc', models.CharField(default=None, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Ponds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_name', models.CharField(default=None, max_length=240)),
                ('pond_length', models.FloatField(null=True)),
                ('pond_depth', models.FloatField(null=True)),
                ('pond_breadth', models.FloatField(null=True)),
                ('pond_area', models.FloatField(null=True)),
                ('pond_capacity', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('description', models.CharField(default=None, max_length=240)),
                ('createdAt', models.DateField(auto_now=True, null=True)),
                ('lastupdatedt', models.DateField(auto_now=True, null=True)),
                ('pond_number', models.IntegerField(default=0, null=True)),
                ('last_feed_datetime', models.DateField(auto_now=True, null=True)),
                ('last_preparation_time', models.DateField(auto_now=True, null=True)),
                ('last_stock_date', models.DateField(auto_now=True, null=True)),
                ('current_stock_id', models.IntegerField(default=0, null=True)),
                ('estimated_harvest_date', models.DateField(auto_now=True, null=True)),
                ('is_active_pond', models.BooleanField(default=False)),
                ('active_cycle_id', models.IntegerField(null=True)),
                ('active_cycle_date', models.DateField(null=True)),
                ('no_of_harvests', models.IntegerField(default=0)),
                ('farm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='farms.farms')),
                ('pond_construct_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pond_construct_types', to='ponds.pondconstructtype')),
                ('pond_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pond_types', to='ponds.pondtype')),
            ],
        ),
        migrations.CreateModel(
            name='PondImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='pond_images')),
                ('image_name', models.CharField(default=None, max_length=24, null=True)),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pond_images', to='ponds.ponds')),
            ],
        ),
    ]
