# Generated by Django 3.2.14 on 2022-10-04 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.IntegerField(choices=[(1, 'Vennamai')], default='1', null=True)),
                ('species_pl_stage', models.IntegerField(choices=[(1, 'PL-5'), (2, 'PL-10'), (3, 'PL-15')], default='1', null=True)),
                ('invest_amount', models.IntegerField(default=0, null=True)),
                ('pondPrep_cost', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('lastupdatedt', models.DateField(auto_now=True)),
                ('seeding_qty', models.IntegerField(default=None, null=True)),
                ('seeding_date', models.DateField(default=datetime.date.today)),
                ('numbers_of_larva', models.IntegerField(default=6000)),
                ('harvest_id', models.IntegerField(null=True)),
                ('Pond', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponds.ponds')),
                ('seed_company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CycleSeedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=400, null=True)),
                ('image', models.FileField(null=True, upload_to='seed_images')),
                ('images', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seed_images', to='cycle.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='CyclePondImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=400, null=True)),
                ('image', models.FileField(null=True, upload_to='pond_images')),
                ('images', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pond_images', to='cycle.cycle')),
            ],
        ),
    ]
