# Generated by Django 3.2.14 on 2022-08-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('sic_gst_code', models.CharField(default='', max_length=200)),
                ('pan_no', models.CharField(default='', max_length=200)),
                ('address_one', models.TextField(default='')),
                ('address_two', models.TextField(default='')),
                ('pincode', models.IntegerField(default=0)),
                ('website', models.URLField(default='')),
            ],
        ),
    ]
