# Generated by Django 3.2.14 on 2022-10-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_2_code', models.IntegerField(null=True)),
                ('alpha_3_code', models.IntegerField(null=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('country_name', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('fraction_unit', models.IntegerField(null=True)),
                ('fraction_number', models.IntegerField(null=True)),
                ('iso_code', models.IntegerField(null=True)),
                ('symbol', models.CharField(max_length=400, null=True)),
                ('currency', models.CharField(default='ruppes', max_length=400, null=True)),
                ('coutry_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country')),
            ],
        ),
    ]
