# Generated by Django 3.2.14 on 2022-10-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, null=True)),
                ('product_desc', models.CharField(max_length=250, null=True)),
                ('image', models.FileField(null=True, upload_to='speciespicture_uploads')),
                ('fish_common_name', models.CharField(max_length=250, null=True)),
                ('fish_scientific_name', models.CharField(max_length=250, null=True)),
                ('fish_ranges', models.IntegerField(null=True)),
                ('wikipedia', models.CharField(max_length=250, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('exp', models.IntegerField(null=True)),
                ('parent_category', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField()),
                ('desc', models.CharField(max_length=250, null=True)),
                ('image_url', models.URLField()),
                ('species_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_category', to='species.species')),
            ],
        ),
    ]
